version: '3.7'

services:
  searxng:
    image: paulgoio/searxng:production
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    environment:
      - IMAGE_PROXY=true
      - BASE_URL=http://127.0.0.1
      - NAME=2FINE
      - CONTACT=404 not found
    
      - GIT_BRANCH=main
